# Site
repository: gelsleichter/en_resume
favicon: images/favicon.ico

# Personal info
name: Yuri Gelsleichter
title: Doctor in Science, Technology and Innovation in Agriculture [CV em Português 🇧🇷](https://gelsleichter.github.io/port_resume/)
email: yurigelsleichter@gmail.com
# website: https://gelsleichter.github.io/ 
website: https://datasitu.com

# Social links
# twitter_username: facespics
github_username:  Gelsleichter
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: gelsleichteryuri
linkedin_username: yurigelsleichter
# pinterest_username: jekyll
# youtube_username: YuriGelsleichter
# googleplus_username: +jekyll

# About Section 
about_title: About me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Yuri Andrei Gelsleichter, Mechanical Technician (IFSC, 2004), Environmental Engineer (UNISUL, 2015), PhD in Science, 
  Technology and Innovation in Agriculture (UFRRJ, 2020), Postdoctoral Researcher (Hungarian University of Agricultural Sciences, 2023). 
  
  During this journey I became a specialist in Digital Soil and Environment Mapping, Precision Agriculture, 
  Analysis and Data Visualization applying the R programming language. 
  
  Currently also working with remote sensing, data mining and automation, and research in the area of soil classification and 
  spectroradiometry and precision agriculture. Co-funder of (Data Situ](https://datasitu.com).
   
# Projects Section 
projects_title: Projects

# Experience Section 
experience_title: International Experiences 

# Education Section 
educaton_title: Education 

# More Section
more_title: A Little More About Me 
more_content: | # this will include new lines to allow paragraphs
  Trabalhos mais relevantes: 
  
  Enhancing Soil Mapping with Hyperspectral Subsurface Images generated from soil lab Vis-SWIR spectra tested in southern Brazil; 2023; 
  Gelsleichter, Y.A.; Costa, E.M,; Anjos, L.H.C.; Marcondes, R.A.T; [doi](https://doi.org/10.1016/j.geodrs.2023.e00641)
  
  Past and Future Responses of Soil Water to Climate Change in Tropical and Subtropical Rainforest Systems in South America; 2023; 
  Arévalo, S.M.M.; Delgado, R.C.; Lindemann, D.S.; Gelsleichter, Y.A.; Pereira, M.G.; Rodrigues, R.A.; Justino, F.B.; Wanderley, H.S.; 
  Zonta, E.; Santana, R.O.; Souza; R.S.; [doi](https://doi.org/10.3390/atmos14040755)
  
  Degradation of South American biomes: What to expect for the future?; Delgado, R.C.; Santana, R.O.; Gelsleichter, Y.A.; 
  Pereira, M.G.; [doi](https://doi.org/10.1016/j.eiar.2022.106815)
  
  Mapping soil properties in a poorly-accessible area; Costa, E.M.; Pinheiro, H.S.K.; Anjos, L.H.C; Marcondes, R.A.T.; 
  Gelsleichter, Y.A.; [doi](https://doi.org/10.36783/18069657rbcs20190107)
  
  Spatial Bayesian belief networks: a participatory approach for mapping environmental vulnerability at the Itatiaia National Park, Brazil; 
  Costa, E.M.; Pinheiro, H.S.K.; Anjos, L.H.C; Gelsleichter, Y.A.; Marcondes, R.A.T.; [doi](https://doi.org/10.1007/s12665-020-09099-9)
   
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
