# Site
repository: gelsleichter/en_resume
favicon: images/favicon.ico

# Personal info
name: Yuri Gelsleichter
title: Doctor in Science, Technology and Innovation in Agriculture 
email: brett.h@email.co.uk
website: https://gelsleichter.github.io/

# Social links
# twitter_username: facespics
github_username:  Gelsleichter
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: YuriGelsleichter
linkedin_username: YuriGelsleichter
# pinterest_username: jekyll
youtube_username: YuriGelsleichter
# googleplus_username: +jekyll

# About Section 
about_title: About me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yuri and I'm a specialist in Soil Mapping and remote Senssing. As well as R programing Language. 
  I am most skilled in: <mark>R coding</mark> and <mark>GIS</mark>.  [This resume in Portuguese](https://gelsleichter.github.io/port_resume/) (Veja este currículo em português) ::brazil::  <i class="france flag"></i>
  
# Projects Section 
projects_title: My Projects

# Experience Section 
# experience_title: Experience 

# Education Section 
# educaton_title: Education 

# internation xp Section
intexperience_title: International Experiences
intexperience_content: | # this will include new lines to allow paragraphs
  Schollarships
   - Hungary 2013-2014, Undergrad Level (Brazilian Govenament, CAPES)
   - Hungary 2017-2018, PhD level, contribution on Universal Soil Classification Systems
   - The Netherlands, [ISRIC](https://www.isric.org/), Development of Landuse Scenarios for future soil carbon stocks
   
# More Section
more_title: A Little More About Me 
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
   - <i class="france flag"></i>


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
